version: "3.5"

services:
  frontend_server:
    image: frontend
    build: ./frontend
    ports:
      - 9210:9210
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9211
    container_name: frontend

  backend_server:
    image: backend
    build: ./backend
    ports:
      - 9211:9211
    environment:
      - PORT=9211
      - REDIS_HOST=redis_server
      - POSTGRES_HOST=postgres_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost

    container_name: backend
    depends_on:
      - postgres_server
      - redis_server

  redis_server:
    image: redis
    restart: unless-stopped
    container_name: redis

  postgres_server:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    volumes:
      - database:/var/lib/postgresql/data

  reverse_proxy:
    image: reverse_proxy
    build: ./nginx
    restart: unless-stopped
    ports:
      - 9212:9212
    depends_on:
      - frontend_server
      - backend_server

volumes:
  database:
